#!/usr/bin/env bash
# Run this from the root directory

cd ./test || exit 1
source approvals.bash

export REPLICATE_HOST=http://localhost:3000
export REPLICATE_API_TOKEN=no-token-needed
export REPLI_TEMPLATES_DIR=tmp/templates
export REPLI_LOG_LEVEL=debug

if [ "$(curl -s ${REPLICATE_HOST}/ | jq -r '."mock server status"')" != "running" ]; then
  fail "mock server not running, testing is aborted"
fi

describe "help"
  allow_diff "\/home\/[^\/]*"
  approve "repli --help"
  approve "repli"

describe "new"
  approve "repli new --help"

describe "get"
  approve "repli get --help"

describe "info"
  approve "repli info --help"
  approve "repli info"
  approve "repli info google/nano-banana"
  approve "repli info google/nano-banana --json"

describe "templates"
  approve "repli templates --help"
  approve "repli templates"

describe "templates new"
  approve "repli templates new --help"
  approve "repli templates new"

describe "templates list"
  approve "repli templates list --help"
  approve "repli templates list"

describe "files"
  approve "repli files --help"
  approve "repli files"

describe "files list"
  approve "repli files list --help"
  approve "repli files list"

describe "files upload"
  approve "repli files upload --help"
