#!/usr/bin/env bash
#!/usr/bin/env bash
set -euo pipefail
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
cd "$tmpdir"
wget -q https://github.com/DannyBen/ssi/releases/latest/download/ssi
chmod +x ssi

./ssi bin https://github.com/DannyBen/repli/releases/latest/download/repli
repli --version
