#!/usr/bin/env bash
set -euo pipefail

# === Setup SSI ===

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
cd "$tmpdir"
export PATH="$tmpdir:$PATH"

if command -v wget >/dev/null 2>&1; then
  wget -q -O ssi https://github.com/DannyBen/ssi/releases/download/v0.1.3/ssi
elif command -v curl >/dev/null 2>&1; then
  curl -fSsL https://github.com/DannyBen/ssi/releases/download/v0.1.3/ssi -o ssi
else
  echo "Error: please install wget or curl, then try again" >&2
  exit 1
fi
chmod +x ssi

# === Install ===

ssi log info Downloading latest executable
ssi install bin https://github.com/DannyBen/repli/releases/latest/download/repli
ssi log info "repli --version : $(repli --version)"
