#!/usr/bin/env bash
set -euo pipefail
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
cd "$tmpdir"
wget -q https://github.com/DannyBen/ssi/releases/latest/download/ssi
chmod +x ssi

./ssi log info Downloading latest executable
./ssi bin https://github.com/DannyBen/repli/releases/latest/download/repli
./ssi log info "repli --version : $(repli --version)"
